# Use the official Node.js LTS image as the base image
FROM node:lts

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the server app files to the container
COPY . .

# Expose the app port
EXPOSE 3042

# Start the server app
CMD ["nodemon", "index"]
