# Use the official Node.js LTS image as the base image
FROM node:lts

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the client app files to the container
COPY . .

# Build the client app
RUN npm run build

# Expose the app port
EXPOSE 5173

# Start the client app
CMD ["npm", "run", "dev"]
